# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - 'REL_*'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getinstaller:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache PostgreSQL installer
        uses: actions/cache@v4
        id: cachePostgresInstaller
        with:
          path: C:\OTHERBIN\postgresql_install.exe
          key: postgresql_installer
      - name: Download postgresql install from EDB
        uses: suisei-cn/actions-download-file@v1.6.0
        if: ${{steps.cachePostgresInstaller.outputs.cache-hit != 'true'}}
        id: downloadPostgresInstaller
        with:
          retry-times: 1
          url: https://sbp.enterprisedb.com/getfile.jsp?fileid=1258893
          target: c:\OTHERBIN
          filename: postgresql_install.exe
      - name: install postgresql binary
        shell: cmd
        run: |
            echo on
            C:\OTHERBIN\postgresql_install.exe --mode unattended --unattendedmodeui none --superpassword postgres --enable-components server    
      - name: start postgresql
        shell: cmd
        run: |
            echo on
            sc config "postgresql-x64-16" start= auto     
      - name: publish release
        if: startsWith(github.ref, 'refs/tags/REL_')
        shell: cmd
        run: echo "hello world"
